### ISSUE TITLE
NodeExecutorPackage fails to load

### ISSUE THREAD

**Issue by ghost** [madskristensen/NodeExecutor#2]
### Installed product versions
- Visual Studio 2017 Community
- Node Executor

### Description
After booting VS 2017 Community Edition, loading a solution causes an error with the NodeExecutorPackage. No errors are displayed when closing and re-opening the solution. It does display for each instance if multiple instances of VS are running. This happens on more than one solution.

The content below is from the activity log:

SetSite failed for package [NodeExecutorPackage]Source: 'Microsoft.VisualStudio.Shell.14.0' Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService. System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService. at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType) at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType) at System.ComponentModel.Design.MenuCommandService.GetService(Type serviceType) at System.ComponentModel.Design.MenuCommandService.EnsureVerbs() at System.ComponentModel.Design.MenuCommandService.FindCommand(Guid guid, Int32 id) at System.ComponentModel.Design.MenuCommandService.FindCommand(CommandID commandID) at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command) at NodeExecutor.ExecuteCommand..ctor(Package package, OleMenuCommandService commandService) in C:\projects\nodeexecutor\src\Commands\ExecuteCommand.cs:line 25 at NodeExecutor.NodeExecutorPackage.<InitializeAsync>d_0.MoveNext() in C:\projects\nodeexecutor\src\NodeExecutorPackage.cs:line 21 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Shell.AsyncPackage.<>cDisplayClass16_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b_1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck) at Microsoft.VisualStudio.Services.VsTask.GetResult() 

### Steps to recreate
1. Boot VS2017.
2. Open a solution. 
3. Error message appears.

### Current behavior
The executor fails to load.

### Expected behavior
The executor should load without issue.

**Comment by madskristensen** [comment]
This should be fixed in the latest release version 0.5.8. Can you verify you are on the latest release, please?

**Comment by ghost** [comment]
It's fixed in 0.5.8.
